### ISSUE TITLE
请求更新一版支持spring cloud alibaba 2022.0.0.0-RC2的

### ISSUE THREAD

**Issue by Lu-Lucifer** [mfish-qf/mfish-nocode#169]
spring cloud alibaba 2022.0.0.0-RC2支持了spirngboot3和Spring Cloud 2022，不知道可不可以开个分支，支持一版最新的，来尝尝鲜啊

**Comment by mfish-qf** [comment]
后面会升级，持续关注吧

**Comment by mfish-qf** [comment]
已升级springCloud2022
