### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by kangzemin** [mfish-qf/mfish-nocode#173]
构建失败，执行步骤如下：
step1： git clone https://github.com/mfish-qf/mfish-nocode
step2:   mvn clean
step3:   mvn package
错误信息：
![image](https://github.com/mfish-qf/mfish-nocode/assets/40269690/d8dc8340-470e-4e92-9770-efdb3889b86d)

环境信息：
[root@VM-4-2-centos mfish-nocode]# java -version
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)
[root@VM-4-2-centos mfish-nocode]# mvn -v
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-15T01:29:23+08:00)
Maven home: /usr/local/maven
Java version: 17.0.7, vendor: Oracle Corporation
Java home: /opt/java17
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.71.1.el7.x86_64", arch: "amd64", family: "unix"

**Comment by mfish-qf** [comment]
jdk用oracle版本的1.8试试
