### ISSUE TITLE
代码生成可以将生成的代码创建文件到指定路径嘛

### ISSUE THREAD

**Issue by Lu-Lucifer** [mfish-qf/mfish-nocode#180]
使用了这个项目后，我发现虽然有代码生成的，也有下载代码，但是感觉还是不太方便。

如果能在界面上面有设置相关模版生成后的代码保存路径，然后有按钮，能将对应的代码直接保存到指定位置，这就真的能好好摸鱼了

**Comment by mfish-qf** [comment]
因为是微服务架构，目录比较多。具体生成到哪个目录需要人工判断。覆盖一下也耽误不了几分钟

**Comment by zibo2019** [comment]
够懒！

**Comment by Lu-Lucifer** [comment]
@zibo2019 这个不懒怎么提现出用这个项目能摸鱼呢

**Comment by mfish-qf** [comment]
开发环境代码保存到指定路径已经升级
