### ISSUE TITLE
这个列展示  能不能弄成根据账号来设置  

### ISSUE THREAD

**Issue by xcf-jiuyujiuan** [mfish-qf/mfish-nocode#296]
![866d18be598a5dd3aa1e1ae69e43ab87](https://github.com/user-attachments/assets/e0f2eaa3-cdb2-4e6b-9efd-902fd9d9c3a6)
**因为有的人员他就喜欢他自己的******

**Comment by mfish-qf** [comment]
该功能已添加到main分支，sys_config需要增加字段
