### ISSUE TITLE
可以支持用户提交建表语句吗

### ISSUE THREAD

**Issue by sunl888** [mfish-qf/mfish-nocode#305]
可以支持用户提交建表语句吗，我想提交建表语句到平台提供的数据库中，然后生成代码，不知道能不能这样玩

**Comment by mfish-qf** [comment]
数据源配置你的库就行了

**Comment by sunl888** [comment]
我们是在公司电脑开发的，公司不允许暴露数据库(^_^)v  如果能用你们平台的数据库创建表就好了，用完即删的那种

**Comment by mfish-qf** [comment]
你开发也得连数据库啊

**Comment by mfish-qf** [comment]
我生成的代码是基于我平台使用的，你的用我框架连自己数据库开发

**Comment by sunl888** [comment]
哦哦 好的
